WCS\TerrainBundle\Entity\Terrain:
    type: entity
    table: null
    repositoryClass: WCS\TerrainBundle\Entity\TerrainRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        latitude:
            type: float
        longitude:
            type: float
    lifecycleCallbacks: {  }
